version: '3'

services:
  backend-django:
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - "./.env.dev"
    depends_on:
      - db-postgres

  db-postgres:
    image: postgres:12-alpine
    env_file:
      - "./.env.dev"
    ports:
      - 5432:5432